modLoader = "javafml"
loaderVersion = "[43,)"
license = "LGPL-2.1-only"

[[mods]]
modId = "memoryleakfix"
version = "${version}"
displayName = "MemoryLeakFix"
displayURL="https://github.com/TexTrueStudio/MemoryLeakFix" #optional
logoFile="./assets/memoryleakfix/icon.png" #optional
credits="FX - PR0CESS" #optional
authors="TexTrue, ThinkingStudio" #optional
description = '''
Memory Leak Fix unoffical forge port.
A mod which fixes multiple memory leaks, both client-side & server-side.
'''

[[dependencies.memoryleakfix]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.memoryleakfix]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"